name: Update Commit Snake

on:
  schedule:
    - cron: '0 */12 * * *'
  workflow_dispatch:

jobs:
  snake:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout main
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Generate commit-snake SVG
        uses: Platane/snk@master
        with:
          github_user_name: 'gabrielmelim'
          svg_out_path: 'snake/github-contribution-grid-snake.svg'
          theme: 'dark'

      - name: Commit & Push
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add snake/github-contribution-grid-snake.svg
          git diff --cached --exit-code || (
            git commit -m "chore: update commit snake"
            git push
          )
