# .github/workflows/update-snake.yml
name: Update Commit Snake

on:
  schedule:
    # executa a cada 12h
    - cron: '0 */12 * * *'
  workflow_dispatch:

jobs:
  snake:
    runs-on: ubuntu-latest
    steps:
      # 1) Checkout da main
      - name: Checkout main
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      # 2) Gera só o SVG do snake
      - name: Generate Commit Snake SVG
        uses: Platane/snk/svg-only@v3
        with:
          # seu usuário no GitHub
          github_user_name: 'gabrielmelim'
          # onde salvar e qual tema usar
          outputs: |
            snake/github-contribution-grid-snake.svg?palette=github-dark

      # 3) Commit & Push do SVG
      - name: Commit & Push updated snake
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add snake/github-contribution-grid-snake.svg
          git diff --cached --exit-code || (
            git commit -m "chore: update commit snake"
            git push
          )
