name: Update Commit Snake

on:
  schedule:
    # executa a cada 12 horas
    - cron: '0 */12 * * *'
  workflow_dispatch:

jobs:
  snake:
    runs-on: ubuntu-latest

    steps:
      # 1) Faz checkout da branch main
      - name: Checkout main
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      # 2) Gera o SVG do commit‑snake via platane/snk-action
      - name: Generate Commit Snake SVG
        uses: platane/snk-action@v1
        with:
          github_user_name: 'gabrielmelim'
          svg_out_path: 'snake/github-contribution-grid-snake.svg'
          # passa flags extras como --theme
          args: '--theme dark'

      # 3) Commit & Push do SVG gerado
      - name: Commit & Push updated snake
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add snake/github-contribution-grid-snake.svg
          git diff --cached --exit-code || (
            git commit -m "chore: update commit snake"
            git push
          )
